### ISSUE TITLE
Bug. Characters are NOT moved together with the task station in v. 2.4.2

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1687] opened 2023-11-25 18:24 UTC
A character that is accidentally moved under the floor level cannot be moved anymore.

**Comment by fwild** [comment] 2023-11-25 18:25
not in 2.5RC, I just tried it.

**Comment by fominykh** [comment] 2023-11-25 18:28
A related question: the "locked" augmentations are also not moved together with the task station. Is this intentional?

**Comment by fwild** [comment] 2023-11-30 16:37
Not moving with task station: makes sense. As this is not a bug in RC 2.5, I am closing it, btw.

**Closed as completed by fwild** 2023-11-30 16:37 UTC
Labels: bug
