### ISSUE TITLE
Merge ghost and character model?

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#841] opened 2022-03-04 22:43 UTC
In GitLab by @wild on Mar 4, 2022, 23:43

The ghost and the character models could be one - either adding manipulation functionality for the path (and hands paths) to the ghost, or converting ghost recording to a path and animation for the character model. This is an interesting idea - but still probably in the distant future. 

This issue serves discussion on how this could be implemented - and what the disadvantages and risks are.

**Comment by fwild** [comment] 2022-06-08 13:35
Dupe of https://github.com/WEKIT-ECS/MIRAGE-XR/issues/944, closing.

**Closed as completed by fwild** 2022-06-08 13:35 UTC
Labels: requires discussion
