### ISSUE TITLE
GhostTrack: add finger tracking

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#488] opened 2021-07-01 13:40 UTC
In GitLab by @wild on Jul 1, 2021, 15:40

MRTk now allows for tracking fingers - we should add this for the ghost (making sure that on mobiles - and HL1? it has a graceful degradation).

**Comment by fwild** [comment] 2022-06-08 13:19
This is a duplicate of https://github.com/WEKIT-ECS/MIRAGE-XR/issues/871 - therefore closing this ticket.

**Closed as completed by fwild** 2022-06-08 13:19 UTC
