### ISSUE TITLE
Occlusion handling for augmentations in PlayMode

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#847] opened 2022-03-04 22:50 UTC
In GitLab by @wild on Mar 4, 2022, 23:50

PlayMode should handle occlusion of any augmentation. EditMode not.

**Comment by fwild** [comment] 2024-03-26 15:37
dupe of https://github.com/WEKIT-ECS/MIRAGE-XR/issues/560, closing.

**Closed as completed by fwild** 2024-03-26 15:37 UTC
Labels: priority: high
