### ISSUE TITLE
Mobile: Character model: context panel fiddely to use

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#686] opened 2021-11-02 15:06 UTC
In GitLab by @wild on Nov 2, 2021, 16:06

The edit panel for the character model (the one to its right) is fiddly to use on mobiles - we need this to be with a screen space menu.

**Comment by fwild** [comment] 2022-06-08 14:02
Dupe of https://github.com/WEKIT-ECS/MIRAGE-XR/issues/854, closing this one.

**Closed as completed by fwild** 2022-06-08 14:02 UTC
Labels: mobile, priority: high
